### ISSUE TITLE
301 redirect api url

### ISSUE THREAD

**Issue by MathiasLund** [abiosoft/caddy-docker#59] opened 2017-06-21 21:02 UTC
Hi there, great repo!

I have a question regarding 301 redirects.
I have an app that listens to a web server on url: `http://app.example.com`, but now I've set up https with this repo, and it redirects all http requests to https.

So far so good.
But I found that the app doesn't work now because it requests the `http` version, and the endpoint keeps returning `301 Moved Permanently`. 

What do I do?  
I've updated the URL in the app to https, but obviously I also want the http app-version to work.

How can I make the http route work again?

**Comment by abiosoft** [comment] 2017-06-21 21:20
Caddy does that if you're using automatic https. Except you wanna use http only or manually specify certs. 

Anyway I'll be closing this because it is Caddy's behaviour and not caused by this docker image.

**Closed by abiosoft** 2017-06-21 21:20 UTC

**Comment by dodekeract** [comment] 2017-06-21 22:19
@MathiasLund I suggest you fix the app instead of caddy. HTTP is **not acceptable** in 2017.
