### ISSUE TITLE
Permission denied when binding to :443

### ISSUE THREAD

**Issue by iCreateJB** [abiosoft/caddy-docker#27] opened 2016-09-21 12:11 UTC
On the latest release I get a permission error when attempting to bind to 443: 

`443: bind: permission denied`

[command]
`docker run -d -p 80:80 -p 443:443 --name caddy -v $(pwd)/Caddyfile:/etc/Caddyfile -v $(pwd):/srv -v $(pwd):/root/.caddy abiosoft/caddy`

Rolling back to 0.9.0 resolves the error. 

I noticed that the user changed per your comment in another ticket, non-root now using `caddy`. 

Would setcap resolve the permissions issue ?

**Comment by abiosoft** [comment] 2016-09-21 14:06
use `/home/caddy/.caddy` instead

**Comment by abiosoft** [comment] 2016-09-21 14:13
Sorry, I could not reproduce this. Have you updated your images ?

**Comment by iCreateJB** [comment] 2016-09-21 14:22
Just pulled the latest: 

`sudo docker run -d -p 80:80 -p 443:443 --name caddy -v $(pwd)/Caddyfile:/etc/Caddyfile -v $(pwd):/srv -v $(pwd):/home/caddy/.caddy abiosoft/caddy
651d87dee4c3517be4bc7abc6ed9850a071f4fcf1c3f6d5c496666e9fb916374`

`sudo docker logs 651d87dee4c3517be4bc7abc6ed9850a071f4fcf1c3f6d5c496666e9fb916374
2016/09/21 14:21:24 stat /home/caddy/.caddy/acme/acme-v01.api.letsencrypt.org/sites/www.jballard.io/www.jballard.io.crt: permission denied
Activating privacy features...`

**Comment by abiosoft** [comment] 2016-09-21 15:41
I have reproduced this. For now, run with `-u root` and use `/root/.caddy` until I fixed this.

Still trying to figure out a way.

**Comment by iCreateJB** [comment] 2016-09-21 15:58
Currently running with the latest: 

` docker run -u root -d -p 80:80 -p 443:443 --name caddy -v $(pwd)/Caddyfile:/etc/Caddyfile -v $(pwd):/srv -v $(pwd):/root/.caddy abiosoft/caddy`

**Comment by abiosoft** [comment] 2016-09-21 16:07
I'll be closing this because the issue was due to docker's volume permissions, not the ability to bind to :443.

A separate issue can be opened for that.

**Closed by abiosoft** 2016-09-21 16:07 UTC

**Comment by abiosoft** [comment] 2016-09-29 20:43
Hi, I had to revert the user update due to so many complaints and inability to find a solution to volume issues. 

You should be able to use `docker run -d -p 80:80 -p 443:443 --name caddy -v $(pwd)/Caddyfile:/etc/Caddyfile -v $(pwd):/srv -v $(pwd):/root/.caddy abiosoft/caddy` without any problems bow.

**Comment by iCreateJB** [comment] 2016-09-29 23:33
Would set_cap have worked for the user you modified ?

**Comment by abiosoft** [comment] 2016-09-30 04:36
I already used setcap, that's why the user was able to bind to any port. 

The main problem was that any mounted volume is owned by root and the caddy user could only read but not write to it. Caddy's automatic https needs to create new directories to store let's encrypt certs.
